### ISSUE TITLE
address can be left blank

### ISSUE THREAD

**Issue by MagneticReaper** [magdalex/GroceryStoreSystem#15]
need to add requirements for a number and a letter (promp user for a stret name and address number). we should probably allow special characters so they can do things like '300 vanier apt#3'

**Comment by magdalex** [comment]
It's possible to accept only # and not all special characters. Will do.

**Comment by MagneticReaper** [comment]
make sure we can write:
3-300 street
300 street apt*3
300 street apt#3
(3) 300 street

you know what... just allow special characters... XD since some streets name have accents and not all input use characters with accents some split them with a special character. like
é and é are not the same. one of them is made up of 2 characters. if you copy paste it in a text editor, you'll see that you can delete the accent without deleting the e on the first one

hmm... i need to check other fields to see if they accept accents

**Comment by magdalex** [comment]
Fair enough; when I wrote the regex I operated under the assumption that most services now have an auto-fill or a way to authenticate the address and reformat it as is registered in google maps. But since we can't do that, i should let users write in their addresses as they want. 
If you want to allow all characters, it's as simple as removing the check.

**Comment by MagneticReaper** [comment]
i think it would still be good to check for at least 1 number and 1 letter
